language: node_js
node_js:
- 8
- 9
- 10
cache: npm
deploy:
  provider: script
  script: bash ./.travis/deploy.sh
  on: master
jobs:
  include:
    - stage: deploy
      node_js: 8
before_install:
- openssl aes-256-cbc -K $encrypted_a9f91507e46a_key -iv $encrypted_a9f91507e46a_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
- chmod +x ./.travis/deploy.sh
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts
- git remote add deploy dokku@$DEPLOY_SERVER:banmanagement.com >/dev/null 2>&1
- git config --global push.default simple
